version: '3'
services:
  web:
    # replace username/repo:tag with your name and image details
    image: geenlai/ghg:1.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
  db:
    image: sameersbn/postgresql:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=ghg
      - POSTGRES_USER=postgres