version: '3'

services:
  web:
    build: .
    command: ./ghg.sh
    depends_on:
      - db
    env_file:
      - ./envfile/test.env
    ports:
      - '80:8888'

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  # The database
  pgvolume: